# Makefile.in generated by automake 1.11.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/mpc
pkgincludedir = $(includedir)/mpc
pkglibdir = $(libdir)/mpc
pkglibexecdir = $(libexecdir)/mpc
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = src/mpc$(EXEEXT)
am__append_1 = src/charset.c
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING INSTALL NEWS depcomp \
	install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_append_compile_flags.m4 \
	$(top_srcdir)/m4/ax_append_flag.m4 \
	$(top_srcdir)/m4/ax_check_compile_flag.m4 \
	$(top_srcdir)/m4/codeset.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" \
	"$(DESTDIR)$(docdir)"
PROGRAMS = $(bin_PROGRAMS)
am__src_mpc_SOURCES_DIST = src/main.c src/list.c src/password.c \
	src/status.c src/util.c src/command.c src/sticker.c src/idle.c \
	src/message.h src/message.c src/search.c src/options.c \
	src/list.h src/password.h src/charset.h src/status.h \
	src/util.h src/command.h src/idle.h src/search.h src/sticker.h \
	src/mpc.h src/options.h src/gcc.h src/charset.c src/dynamic.h \
	src/dynamic.c
am__objects_1 =
am__objects_2 = src_mpc-charset.$(OBJEXT)
am_src_mpc_OBJECTS = src_mpc-main.$(OBJEXT) src_mpc-list.$(OBJEXT) \
	src_mpc-password.$(OBJEXT) src_mpc-status.$(OBJEXT) \
	src_mpc-util.$(OBJEXT) src_mpc-command.$(OBJEXT) \
	src_mpc-sticker.$(OBJEXT) src_mpc-idle.$(OBJEXT) \
	src_mpc-message.$(OBJEXT) src_mpc-search.$(OBJEXT) \
	src_mpc-options.$(OBJEXT) src_mpc-dynamic.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2)
src_mpc_OBJECTS = $(am_src_mpc_OBJECTS)
am__DEPENDENCIES_1 =
src_mpc_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
am__dirstamp = $(am__leading_dot)dirstamp
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(src_mpc_SOURCES)
DIST_SOURCES = $(am__src_mpc_SOURCES_DIST)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(man_MANS)
DATA = $(doc_DATA)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/ted/Software/Source/mpc/mpc-0.22/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AM_CFLAGS = 
AM_CPPFLAGS =  -DNDEBUG
AUTOCONF = ${SHELL} /home/ted/Software/Source/mpc/mpc-0.22/missing --run autoconf
AUTOHEADER = ${SHELL} /home/ted/Software/Source/mpc/mpc-0.22/missing --run autoheader
AUTOMAKE = ${SHELL} /home/ted/Software/Source/mpc/mpc-0.22/missing --run automake-1.11
AWK = gawk
CC = gcc -std=gnu99
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -Wall -Wextra -Wno-deprecated-declarations -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wcast-qual -Wwrite-strings
CPP = gcc -std=gnu99 -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
ICONV_CPPFLAGS = 
ICONV_LIBS = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBMPDCLIENT_CFLAGS =  
LIBMPDCLIENT_LIBS = -lmpdclient  
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/ted/Software/Source/mpc/mpc-0.22/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
MPC_LIBS =  -lnsl
OBJEXT = o
PACKAGE = mpc
PACKAGE_BUGREPORT = musicpd-dev-team@lists.sourceforge.net
PACKAGE_NAME = mpc
PACKAGE_STRING = mpc 0.22
PACKAGE_TARNAME = mpc
PACKAGE_URL = 
PACKAGE_VERSION = 0.22
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = /usr/local/lib/pkgconfig:/opt/opencv/lib/pkgconfig
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.22
abs_builddir = /home/ted/Software/Source/mpc/mpc-0.22
abs_srcdir = /home/ted/Software/Source/mpc/mpc-0.22
abs_top_builddir = /home/ted/Software/Source/mpc/mpc-0.22
abs_top_srcdir = /home/ted/Software/Source/mpc/mpc-0.22
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/ted/Software/Source/mpc/mpc-0.22/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
AUTOMAKE_OPTIONS = foreign 1.10 dist-bzip2
man_MANS = doc/mpc.1
doc_DATA = AUTHORS COPYING NEWS README \
	doc/mpd-m3u-handler.sh doc/mpd-pls-handler.sh doc/mppledit \
	doc/mpc-completion.bash

EXTRA_DIST = $(man_MANS) $(doc_DATA)
src_mpc_headers = \
	src/list.h \
	src/password.h \
	src/charset.h \
	src/status.h \
	src/util.h \
	src/command.h \
	src/idle.h \
	src/search.h \
	src/sticker.h \
	src/mpc.h \
	src/options.h \
	src/gcc.h

src_mpc_SOURCES = src/main.c src/list.c src/password.c src/status.c \
	src/util.c src/command.c src/sticker.c src/idle.c src/dynamic.c \
	src/message.h src/message.c src/search.c src/options.c \
	$(src_mpc_headers) $(am__append_1)
src_mpc_CPPFLAGS = $(AM_CPPFLAGS) $(ICONV_CFLAGS) $(LIBMPDCLIENT_CFLAGS)
src_mpc_LDADD = $(MPC_LIBS) $(ICONV_LIBS) $(LIBMPDCLIENT_LIBS) -lpthread -lncursesw

# sparse is a semantic parser
# URL: git://www.kernel.org/pub/scm/devel/sparse/sparse.git
SPARSE = sparse
SPARSE_FLAGS = 
SPARSE_CPPFLAGS = $(DEFAULT_INCLUDES) \
	-I$(shell $(CC) -print-file-name=include) \
	-I$(shell $(CC) -print-file-name=include-fixed)

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/mpc$(EXEEXT): $(src_mpc_OBJECTS) $(src_mpc_DEPENDENCIES) $(EXTRA_src_mpc_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/mpc$(EXEEXT)
	$(LINK) $(src_mpc_OBJECTS) $(src_mpc_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/src_mpc-charset.Po
include ./$(DEPDIR)/src_mpc-command.Po
include ./$(DEPDIR)/src_mpc-idle.Po
include ./$(DEPDIR)/src_mpc-list.Po
include ./$(DEPDIR)/src_mpc-main.Po
include ./$(DEPDIR)/src_mpc-message.Po
include ./$(DEPDIR)/src_mpc-options.Po
include ./$(DEPDIR)/src_mpc-password.Po
include ./$(DEPDIR)/src_mpc-dynamic.Po
include ./$(DEPDIR)/src_mpc-search.Po
include ./$(DEPDIR)/src_mpc-status.Po
include ./$(DEPDIR)/src_mpc-sticker.Po
include ./$(DEPDIR)/src_mpc-util.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

src_mpc-main.o: src/main.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-main.o -MD -MP -MF $(DEPDIR)/src_mpc-main.Tpo -c -o src_mpc-main.o `test -f 'src/main.c' || echo '$(srcdir)/'`src/main.c
	$(am__mv) $(DEPDIR)/src_mpc-main.Tpo $(DEPDIR)/src_mpc-main.Po
#	source='src/main.c' object='src_mpc-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-main.o `test -f 'src/main.c' || echo '$(srcdir)/'`src/main.c

src_mpc-main.obj: src/main.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-main.obj -MD -MP -MF $(DEPDIR)/src_mpc-main.Tpo -c -o src_mpc-main.obj `if test -f 'src/main.c'; then $(CYGPATH_W) 'src/main.c'; else $(CYGPATH_W) '$(srcdir)/src/main.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-main.Tpo $(DEPDIR)/src_mpc-main.Po
#	source='src/main.c' object='src_mpc-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-main.obj `if test -f 'src/main.c'; then $(CYGPATH_W) 'src/main.c'; else $(CYGPATH_W) '$(srcdir)/src/main.c'; fi`

src_mpc-list.o: src/list.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-list.o -MD -MP -MF $(DEPDIR)/src_mpc-list.Tpo -c -o src_mpc-list.o `test -f 'src/list.c' || echo '$(srcdir)/'`src/list.c
	$(am__mv) $(DEPDIR)/src_mpc-list.Tpo $(DEPDIR)/src_mpc-list.Po
#	source='src/list.c' object='src_mpc-list.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-list.o `test -f 'src/list.c' || echo '$(srcdir)/'`src/list.c

src_mpc-list.obj: src/list.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-list.obj -MD -MP -MF $(DEPDIR)/src_mpc-list.Tpo -c -o src_mpc-list.obj `if test -f 'src/list.c'; then $(CYGPATH_W) 'src/list.c'; else $(CYGPATH_W) '$(srcdir)/src/list.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-list.Tpo $(DEPDIR)/src_mpc-list.Po
#	source='src/list.c' object='src_mpc-list.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-list.obj `if test -f 'src/list.c'; then $(CYGPATH_W) 'src/list.c'; else $(CYGPATH_W) '$(srcdir)/src/list.c'; fi`

src_mpc-password.o: src/password.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-password.o -MD -MP -MF $(DEPDIR)/src_mpc-password.Tpo -c -o src_mpc-password.o `test -f 'src/password.c' || echo '$(srcdir)/'`src/password.c
	$(am__mv) $(DEPDIR)/src_mpc-password.Tpo $(DEPDIR)/src_mpc-password.Po
#	source='src/password.c' object='src_mpc-password.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-password.o `test -f 'src/password.c' || echo '$(srcdir)/'`src/password.c

src_mpc-password.obj: src/password.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-password.obj -MD -MP -MF $(DEPDIR)/src_mpc-password.Tpo -c -o src_mpc-password.obj `if test -f 'src/password.c'; then $(CYGPATH_W) 'src/password.c'; else $(CYGPATH_W) '$(srcdir)/src/password.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-password.Tpo $(DEPDIR)/src_mpc-password.Po
#	source='src/password.c' object='src_mpc-password.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-password.obj `if test -f 'src/password.c'; then $(CYGPATH_W) 'src/password.c'; else $(CYGPATH_W) '$(srcdir)/src/password.c'; fi`

src_mpc-status.o: src/status.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-status.o -MD -MP -MF $(DEPDIR)/src_mpc-status.Tpo -c -o src_mpc-status.o `test -f 'src/status.c' || echo '$(srcdir)/'`src/status.c
	$(am__mv) $(DEPDIR)/src_mpc-status.Tpo $(DEPDIR)/src_mpc-status.Po
#	source='src/status.c' object='src_mpc-status.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-status.o `test -f 'src/status.c' || echo '$(srcdir)/'`src/status.c

src_mpc-status.obj: src/status.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-status.obj -MD -MP -MF $(DEPDIR)/src_mpc-status.Tpo -c -o src_mpc-status.obj `if test -f 'src/status.c'; then $(CYGPATH_W) 'src/status.c'; else $(CYGPATH_W) '$(srcdir)/src/status.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-status.Tpo $(DEPDIR)/src_mpc-status.Po
#	source='src/status.c' object='src_mpc-status.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-status.obj `if test -f 'src/status.c'; then $(CYGPATH_W) 'src/status.c'; else $(CYGPATH_W) '$(srcdir)/src/status.c'; fi`

src_mpc-util.o: src/util.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-util.o -MD -MP -MF $(DEPDIR)/src_mpc-util.Tpo -c -o src_mpc-util.o `test -f 'src/util.c' || echo '$(srcdir)/'`src/util.c
	$(am__mv) $(DEPDIR)/src_mpc-util.Tpo $(DEPDIR)/src_mpc-util.Po
#	source='src/util.c' object='src_mpc-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-util.o `test -f 'src/util.c' || echo '$(srcdir)/'`src/util.c

src_mpc-util.obj: src/util.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-util.obj -MD -MP -MF $(DEPDIR)/src_mpc-util.Tpo -c -o src_mpc-util.obj `if test -f 'src/util.c'; then $(CYGPATH_W) 'src/util.c'; else $(CYGPATH_W) '$(srcdir)/src/util.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-util.Tpo $(DEPDIR)/src_mpc-util.Po
#	source='src/util.c' object='src_mpc-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-util.obj `if test -f 'src/util.c'; then $(CYGPATH_W) 'src/util.c'; else $(CYGPATH_W) '$(srcdir)/src/util.c'; fi`

src_mpc-command.o: src/command.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-command.o -MD -MP -MF $(DEPDIR)/src_mpc-command.Tpo -c -o src_mpc-command.o `test -f 'src/command.c' || echo '$(srcdir)/'`src/command.c
	$(am__mv) $(DEPDIR)/src_mpc-command.Tpo $(DEPDIR)/src_mpc-command.Po
#	source='src/command.c' object='src_mpc-command.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-command.o `test -f 'src/command.c' || echo '$(srcdir)/'`src/command.c

src_mpc-command.obj: src/command.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-command.obj -MD -MP -MF $(DEPDIR)/src_mpc-command.Tpo -c -o src_mpc-command.obj `if test -f 'src/command.c'; then $(CYGPATH_W) 'src/command.c'; else $(CYGPATH_W) '$(srcdir)/src/command.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-command.Tpo $(DEPDIR)/src_mpc-command.Po
#	source='src/command.c' object='src_mpc-command.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-command.obj `if test -f 'src/command.c'; then $(CYGPATH_W) 'src/command.c'; else $(CYGPATH_W) '$(srcdir)/src/command.c'; fi`

src_mpc-sticker.o: src/sticker.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-sticker.o -MD -MP -MF $(DEPDIR)/src_mpc-sticker.Tpo -c -o src_mpc-sticker.o `test -f 'src/sticker.c' || echo '$(srcdir)/'`src/sticker.c
	$(am__mv) $(DEPDIR)/src_mpc-sticker.Tpo $(DEPDIR)/src_mpc-sticker.Po
#	source='src/sticker.c' object='src_mpc-sticker.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-sticker.o `test -f 'src/sticker.c' || echo '$(srcdir)/'`src/sticker.c

src_mpc-sticker.obj: src/sticker.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-sticker.obj -MD -MP -MF $(DEPDIR)/src_mpc-sticker.Tpo -c -o src_mpc-sticker.obj `if test -f 'src/sticker.c'; then $(CYGPATH_W) 'src/sticker.c'; else $(CYGPATH_W) '$(srcdir)/src/sticker.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-sticker.Tpo $(DEPDIR)/src_mpc-sticker.Po
#	source='src/sticker.c' object='src_mpc-sticker.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-sticker.obj `if test -f 'src/sticker.c'; then $(CYGPATH_W) 'src/sticker.c'; else $(CYGPATH_W) '$(srcdir)/src/sticker.c'; fi`

src_mpc-idle.o: src/idle.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-idle.o -MD -MP -MF $(DEPDIR)/src_mpc-idle.Tpo -c -o src_mpc-idle.o `test -f 'src/idle.c' || echo '$(srcdir)/'`src/idle.c
	$(am__mv) $(DEPDIR)/src_mpc-idle.Tpo $(DEPDIR)/src_mpc-idle.Po
#	source='src/idle.c' object='src_mpc-idle.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-idle.o `test -f 'src/idle.c' || echo '$(srcdir)/'`src/idle.c

src_mpc-idle.obj: src/idle.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-idle.obj -MD -MP -MF $(DEPDIR)/src_mpc-idle.Tpo -c -o src_mpc-idle.obj `if test -f 'src/idle.c'; then $(CYGPATH_W) 'src/idle.c'; else $(CYGPATH_W) '$(srcdir)/src/idle.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-idle.Tpo $(DEPDIR)/src_mpc-idle.Po
#	source='src/idle.c' object='src_mpc-idle.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-idle.obj `if test -f 'src/idle.c'; then $(CYGPATH_W) 'src/idle.c'; else $(CYGPATH_W) '$(srcdir)/src/idle.c'; fi`

src_mpc-message.o: src/message.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-message.o -MD -MP -MF $(DEPDIR)/src_mpc-message.Tpo -c -o src_mpc-message.o `test -f 'src/message.c' || echo '$(srcdir)/'`src/message.c
	$(am__mv) $(DEPDIR)/src_mpc-message.Tpo $(DEPDIR)/src_mpc-message.Po
#	source='src/message.c' object='src_mpc-message.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-message.o `test -f 'src/message.c' || echo '$(srcdir)/'`src/message.c

src_mpc-message.obj: src/message.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-message.obj -MD -MP -MF $(DEPDIR)/src_mpc-message.Tpo -c -o src_mpc-message.obj `if test -f 'src/message.c'; then $(CYGPATH_W) 'src/message.c'; else $(CYGPATH_W) '$(srcdir)/src/message.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-message.Tpo $(DEPDIR)/src_mpc-message.Po
#	source='src/message.c' object='src_mpc-message.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-message.obj `if test -f 'src/message.c'; then $(CYGPATH_W) 'src/message.c'; else $(CYGPATH_W) '$(srcdir)/src/message.c'; fi`

src_mpc-search.o: src/search.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-search.o -MD -MP -MF $(DEPDIR)/src_mpc-search.Tpo -c -o src_mpc-search.o `test -f 'src/search.c' || echo '$(srcdir)/'`src/search.c
	$(am__mv) $(DEPDIR)/src_mpc-search.Tpo $(DEPDIR)/src_mpc-search.Po
#	source='src/search.c' object='src_mpc-search.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-search.o `test -f 'src/search.c' || echo '$(srcdir)/'`src/search.c

src_mpc-search.obj: src/search.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-search.obj -MD -MP -MF $(DEPDIR)/src_mpc-search.Tpo -c -o src_mpc-search.obj `if test -f 'src/search.c'; then $(CYGPATH_W) 'src/search.c'; else $(CYGPATH_W) '$(srcdir)/src/search.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-search.Tpo $(DEPDIR)/src_mpc-search.Po
#	source='src/search.c' object='src_mpc-search.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-search.obj `if test -f 'src/search.c'; then $(CYGPATH_W) 'src/search.c'; else $(CYGPATH_W) '$(srcdir)/src/search.c'; fi`

src_mpc-options.o: src/options.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-options.o -MD -MP -MF $(DEPDIR)/src_mpc-options.Tpo -c -o src_mpc-options.o `test -f 'src/options.c' || echo '$(srcdir)/'`src/options.c
	$(am__mv) $(DEPDIR)/src_mpc-options.Tpo $(DEPDIR)/src_mpc-options.Po
#	source='src/options.c' object='src_mpc-options.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-options.o `test -f 'src/options.c' || echo '$(srcdir)/'`src/options.c

src_mpc-options.obj: src/options.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-options.obj -MD -MP -MF $(DEPDIR)/src_mpc-options.Tpo -c -o src_mpc-options.obj `if test -f 'src/options.c'; then $(CYGPATH_W) 'src/options.c'; else $(CYGPATH_W) '$(srcdir)/src/options.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-options.Tpo $(DEPDIR)/src_mpc-options.Po
#	source='src/options.c' object='src_mpc-options.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-options.obj `if test -f 'src/options.c'; then $(CYGPATH_W) 'src/options.c'; else $(CYGPATH_W) '$(srcdir)/src/options.c'; fi`

src_mpc-dynamic.o: src/dynamic.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-dynamic.o -MD -MP -MF $(DEPDIR)/src_mpc-dynamic.Tpo -c -o src_mpc-dynamic.o `test -f 'src/dynamic.c' || echo '$(srcdir)/'`src/dynamic.c
	$(am__mv) $(DEPDIR)/src_mpc-dynamic.Tpo $(DEPDIR)/src_mpc-dynamic.Po

src_mpc-charset.o: src/charset.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-charset.o -MD -MP -MF $(DEPDIR)/src_mpc-charset.Tpo -c -o src_mpc-charset.o `test -f 'src/charset.c' || echo '$(srcdir)/'`src/charset.c
	$(am__mv) $(DEPDIR)/src_mpc-charset.Tpo $(DEPDIR)/src_mpc-charset.Po
#	source='src/charset.c' object='src_mpc-charset.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-charset.o `test -f 'src/charset.c' || echo '$(srcdir)/'`src/charset.c

src_mpc-charset.obj: src/charset.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src_mpc-charset.obj -MD -MP -MF $(DEPDIR)/src_mpc-charset.Tpo -c -o src_mpc-charset.obj `if test -f 'src/charset.c'; then $(CYGPATH_W) 'src/charset.c'; else $(CYGPATH_W) '$(srcdir)/src/charset.c'; fi`
	$(am__mv) $(DEPDIR)/src_mpc-charset.Tpo $(DEPDIR)/src_mpc-charset.Po
#	source='src/charset.c' object='src_mpc-charset.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(src_mpc_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src_mpc-charset.obj `if test -f 'src/charset.c'; then $(CYGPATH_W) 'src/charset.c'; else $(CYGPATH_W) '$(srcdir)/src/charset.c'; fi`
install-man1: $(man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(man_MANS)'; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)
install-docDATA: $(doc_DATA)
	@$(NORMAL_INSTALL)
	@list='$(doc_DATA)'; test -n "$(docdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(docdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(docdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(docdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(docdir)" || exit $$?; \
	done

uninstall-docDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(doc_DATA)'; test -n "$(docdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(docdir)'; $(am__uninstall_files_from_dir)

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@list='$(MANS)'; if test -n "$$list"; then \
	  list=`for p in $$list; do \
	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
	  if test -n "$$list" && \
	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
	    exit 1; \
	  else :; fi; \
	else :; fi
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(MANS) $(DATA) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(docdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-docDATA install-man

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man1

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-docDATA uninstall-man

uninstall-man: uninstall-man1

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-docDATA install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-man install-man1 \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-docDATA uninstall-man uninstall-man1

sparse-check:
	for i in $(src_mpc_SOURCES); \
	do \
		$(SPARSE) -I. $(SPARSE_FLAGS) $(SPARSE_CPPFLAGS) \
			$(src_mpc_CFLAGS) $(src_mpc_CPPFLAGS) \
			$(srcdir)/$$i || exit; \
	done

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
